In [55]:
import pandas as pd
import numpy as np
from sklearn.cross_validation import train_test_split
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_score

In [16]:
nba = pd.read_csv('/Users/kamalesh_das/Desktop/Python/data/nba_2013.csv')

In [17]:
nba.head()

,player,pos,age,bref_team_id,g,gs,mp,fg,fga,fg.,...,drb,trb,ast,stl,blk,tov,pf,pts,season,season_end
0,Quincy Acy,SF,23,TOT,63,0,847,66,141,0.468,...,144,216,28,23,26,30,122,171,2013-2014,2013
1,Steven Adams,C,20,OKC,81,20,1197,93,185,0.503,...,190,332,43,40,57,71,203,265,2013-2014,2013
2,Jeff Adrien,PF,27,TOT,53,12,961,143,275,0.520,...,204,306,38,24,36,39,108,362,2013-2014,2013
3,Arron Afflalo,SG,28,ORL,73,73,2552,464,1011,0.459,...,230,262,248,35,3,146,136,1330,2013-2014,2013
4,Alexis Ajinca,C,25,NOP,56,30,951,136,249,0.546,...,183,277,40,23,46,63,187,328,2013-2014,2013

In [18]:
nba.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 481 entries, 0 to 480
Data columns (total 31 columns):
player          481 non-null object
pos             481 non-null object
age             481 non-null int64
bref_team_id    481 non-null object
g               481 non-null int64
gs              481 non-null int64
mp              481 non-null int64
fg              481 non-null int64
fga             481 non-null int64
fg.             479 non-null float64
x3p             481 non-null int64
x3pa            481 non-null int64
x3p.            414 non-null float64
x2p             481 non-null int64
x2pa            481 non-null int64
x2p.            478 non-null float64
efg.            479 non-null float64
ft              481 non-null int64
fta             481 non-null int64
ft.             461 non-null float64
orb             481 non-null int64
drb             481 non-null int64
trb             481 non-null int64
ast             481 non-null int64
stl             481 non-null int64
blk             481 non-null int64
tov             481 non-null int64
pf              481 non-null int64
pts             481 non-null int64
season          481 non-null object
season_end      481 non-null int64
dtypes: float64(5), int64(22), object(4)
memory usage: 116.6+ KB

In [19]:
nba.describe()

,age,g,gs,mp,fg,fga,fg.,x3p,x3pa,x3p.,...,orb,drb,trb,ast,stl,blk,tov,pf,pts,season_end
count,481.000000,481.000000,481.000000,481.000000,481.000000,481.000000,479.000000,481.000000,481.000000,414.000000,...,481.000000,481.000000,481.000000,481.000000,481.000000,481.000000,481.000000,481.000000,481.000000,481.0
mean,26.509356,53.253638,25.571726,1237.386694,192.881497,424.463617,0.436436,39.613306,110.130977,0.285111,...,55.810811,162.817048,218.627859,112.536383,39.280665,24.103950,71.862786,105.869023,516.582121,2013.0
std,4.198265,25.322711,29.658465,897.258840,171.832793,368.850833,0.098672,50.855639,132.751732,0.157633,...,62.101191,145.348116,200.356507,131.019557,34.783590,30.875381,62.701690,71.213627,470.422228,0.0
min,19.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2013.0
25%,23.000000,32.000000,0.000000,388.000000,47.000000,110.000000,0.400500,0.000000,3.000000,0.234355,...,12.000000,43.000000,55.000000,20.000000,9.000000,4.000000,21.000000,44.000000,115.000000,2013.0
50%,26.000000,61.000000,10.000000,1141.000000,146.000000,332.000000,0.438000,16.000000,48.000000,0.330976,...,35.000000,135.000000,168.000000,65.000000,32.000000,14.000000,58.000000,104.000000,401.000000,2013.0
75%,29.000000,76.000000,54.000000,2016.000000,307.000000,672.000000,0.479500,68.000000,193.000000,0.375000,...,73.000000,230.000000,310.000000,152.000000,60.000000,32.000000,108.000000,158.000000,821.000000,2013.0
max,39.000000,83.000000,82.000000,3122.000000,849.000000,1688.000000,1.000000,261.000000,615.000000,1.000000,...,440.000000,783.000000,1114.000000,721.000000,191.000000,219.000000,295.000000,273.000000,2593.000000,2013.0

In [20]:
# Checking if any feature column having null value or not.
nba.isnull().sum()

player           0
pos              0
age              0
bref_team_id     0
g                0
gs               0
mp               0
fg               0
fga              0
fg.              2
x3p              0
x3pa             0
x3p.            67
x2p              0
x2pa             0
x2p.             3
efg.             2
ft               0
fta              0
ft.             20
orb              0
drb              0
trb              0
ast              0
stl              0
blk              0
tov              0
pf               0
pts              0
season           0
season_end       0
dtype: int64

In [21]:
# fill missing values with the column means
# fill missing values with mean column values 

nba.fillna(nba.mean(), inplace=True)

In [22]:
# Again Checking if any feature column having null value or not.
nba.isnull().any().sum()

0

In [23]:
#Selection of Feature columns
# Removing player name, pos, bref_team_id, pts, season, season_end
X=nba[['age','g','gs','mp','fg','fga','fg.','x3p','x3pa','x3p.','x2p','x2pa','x2p.','efg.','ft','fta','ft.','orb','drb','trb','ast','stl','blk','tov','pf']]
y=nba['pts']

In [28]:
# split into train and test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=707)

In [51]:
# instantiate learning model (k = 3)

#for K in range(1,26):
#    kneigh = KNeighborsRegressor(n_neighbors = K, weights='uniform', algorithm='auto')
#    kneigh.fit(X_train, y_train) 
#    y_pred = kneigh.predict(X_test)
#    print("Accuracy is ", accuracy_score(y_test,y_pred)*100,"% for K-Value:",K)
    
kneigh = KNeighborsRegressor(n_neighbors = 5)
kneigh.fit(X_train, y_train)

KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='minkowski',
          metric_params=None, n_jobs=1, n_neighbors=5, p=2,
          weights='uniform')

In [52]:
# evaluate accuracy
#variance score: 1 is perfect prediction
print('Variance score: %.2f' % kneigh.score(X_test, y_test))

Variance score: 0.98

In [56]:
#cross validation
X1=X.values
y1=y.values
scores = cross_val_score(kneigh, X1,y1, cv=10)
# Print the accuracy for each fold:
print ('Accuracies of 10 folds: ' , scores)
print('-'*80)
# And the mean accuracy of all 10 folds:
print ('Mean accuracy of 10 folds with all columns: ' , scores.mean())

Accuracies of 10 folds:  [0.98815803 0.98292153 0.96015759 0.97811155 0.97877272 0.97774285
 0.97035607 0.96635572 0.98377762 0.97574176]
--------------------------------------------------------------------------------
Mean accuracy of 10 folds with all columns:  0.976209543083091

In [57]:
##Predict the value using test data
pred_test = kneigh.predict(X_test)
# The mean squared error using test data
print("Mean squared error with test data: %.2f"
      % np.mean((pred_test - y_test) ** 2))


##Predict the value using train data
pred_train = kneigh.predict(X_train)
# The mean squared error using train data
print("Mean squared error with train data: %.2f"
      % np.mean((pred_train - y_train) ** 2))

### As both MSE are almost in a same range , 
### hence we can say that model is fitted with both train data and test data

Mean squared error with test data: 4506.39
Mean squared error with train data: 4550.21

In [58]:
import statsmodels.api as sm
from statsmodels.sandbox.regression.predstd import wls_prediction_std

model1=sm.OLS(y_train,X_train)
result=model1.fit()
result.summary()

/anaconda3/lib/python3.6/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                    pts   R-squared:                       1.000
Model:                            OLS   Adj. R-squared:                  1.000
Method:                 Least Squares   F-statistic:                 8.274e+30
Date:                Sat, 15 Sep 2018   Prob (F-statistic):               0.00
Time:                        22:54:20   Log-Likelihood:                 8492.6
No. Observations:                 322   AIC:                        -1.694e+04
Df Residuals:                     300   BIC:                        -1.686e+04
Df Model:                          22
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
age        -8.778e-15   9.02e-15     -0.974      0.331   -2.65e-14    8.96e-15
g           1.443e-14   5.85e-15      2.469      0.014    2.93e-15    2.59e-14
gs          1.332e-15   4.52e-15      0.295      0.768   -7.55e-15    1.02e-14
mp          1.381e-15   3.99e-16      3.460      0.001    5.96e-16    2.17e-15
fg             1.6667   3.04e-15   5.47e+14      0.000       1.667       1.667
fga        -2.082e-15   1.25e-15     -1.662      0.098   -4.55e-15    3.83e-16
fg.        -1.137e-13    2.3e-12     -0.049      0.961   -4.64e-12    4.41e-12
x3p            1.3333   6.37e-15   2.09e+14      0.000       1.333       1.333
x3pa       -1.221e-15   2.59e-15     -0.472      0.638   -6.32e-15    3.88e-15
x3p.        8.882e-14   5.02e-13      0.177      0.860      -9e-13    1.08e-12
x2p            0.3333   4.03e-15   8.26e+13      0.000       0.333       0.333
x2pa       -4.441e-16   1.78e-15     -0.249      0.803   -3.95e-15    3.06e-15
x2p.        2.416e-13   1.09e-12      0.222      0.824    -1.9e-12    2.38e-12
efg.       -8.527e-14   2.07e-12     -0.041      0.967   -4.16e-12    3.99e-12
ft             1.0000   4.22e-15   2.37e+14      0.000       1.000       1.000
fta         2.665e-15   3.39e-15      0.785      0.433   -4.01e-15    9.34e-15
ft.        -2.842e-14   3.43e-13     -0.083      0.934   -7.03e-13    6.46e-13
orb        -2.942e-15   1.98e-15     -1.485      0.139   -6.84e-15    9.58e-16
drb         2.828e-15   1.47e-15      1.922      0.056   -6.76e-17    5.72e-15
trb                 0   7.73e-16          0      1.000   -1.52e-15    1.52e-15
ast        -9.992e-16   1.03e-15     -0.971      0.332   -3.02e-15    1.03e-15
stl        -8.882e-16   3.23e-15     -0.275      0.783   -7.24e-15    5.46e-15
blk        -3.775e-15   3.48e-15     -1.085      0.279   -1.06e-14    3.07e-15
tov        -2.665e-15   3.42e-15     -0.778      0.437    -9.4e-15    4.07e-15
pf         -3.997e-15   2.21e-15     -1.808      0.072   -8.35e-15    3.53e-16
==============================================================================
Omnibus:                       17.195   Durbin-Watson:                   0.998
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               18.451
Skew:                          -0.573   Prob(JB):                     9.85e-05
Kurtosis:                       3.247   Cond. No.                     1.58e+17
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 3.69e-26. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [60]:
# From stats model, we will now consider feature columns where p_values < .05

X_new=nba[['g','mp','fg','x3p','x2p','ft','drb']]
y=nba['pts']
#linear fit

kneigh.fit(X_new, y)
print('Score for these features: ',kneigh.score(X_new, y))

Score for these features:  0.9832645037536917

In [62]:
x_train_2, x_test_2, y_train_2, y_test_2 = train_test_split(
X_new,y, test_size=0.33, random_state=707)
kneigh2 = KNeighborsRegressor(n_neighbors = 5)
# Train the model using the training sets
regrfit2= kneigh2.fit(x_train_2, y_train_2)
scores2 = cross_val_score(regrfit2, X_new.values,y, cv=10)
# Print the accuracy for each fold:
print ('Accuracies of 10 folds: ' , scores2)
print ('Mean accuracy of 10 folds: ' , scores2.mean())

Accuracies of 10 folds:  [0.97547088 0.96622063 0.95893204 0.97566897 0.97790889 0.97924046
 0.96397394 0.96719563 0.98217537 0.97160349]
Mean accuracy of 10 folds:  0.9718390295077104

In [ ]:
#As we can see mean accuracy using first is better than second model. Hence we will use the fisrt model
#to predict the points for NBA players